# Generated by Django 6.0.6 on 2026-07-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aguardando Menu'), (2, 'Aguardando Boas-vindas'), (3, 'Aguardando Informar Faturamento'), (4, 'Informou Despesa'), (5, 'Aguardando Informar Despesa')], default=2),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Faturamento'), (2, 'Despesa')]),
        ),
    ]
