# Generated by Django 6.0.6 on 2026-07-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_alter_transacao_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aguardando Menu'), (2, 'Aguardando Boas-vindas'), (3, 'Aguardando Informar Valor Faturamento'), (4, 'Aguardando Informar Descrição Faturamento'), (5, 'Informou Despesa'), (6, 'Aguardando Informar Mês Faturamento Exclusão'), (15, 'Aguardando Confirmar Exclusão Faturamento'), (17, 'Aguardando Visualizar Faturamento Exclusão'), (20, 'Confirmou ou Cancelou Exclusão Faturamento'), (7, 'Aguardando Informar Despesa'), (8, 'Aguardando Informar Descrição Despesa'), (9, 'Informou Despesa'), (10, 'Aguardando Informar Mês Despesa Exclusão'), (16, 'Aguardando Confirmar Exclusão Despesa'), (18, 'Aguardando Visualizar Despesa Exclusão'), (19, 'Confirmou ou Cancelou Exclusão Despesa'), (11, 'Aguardando Informar Mês Despesa'), (12, 'Aguardando Informar Mês Faturamento'), (13, 'Aguardando Visualizar Despesa'), (14, 'Aguardando Visualizar Faturamento'), (21, 'Aguardando Mês Resumo'), (22, 'Aguardando Ver Resumo')], default=2),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('padrao', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='comum.usuario')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='comum.categoria'),
        ),
    ]
