# Generated by Django 6.0.6 on 2026-07-14 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0006_alter_usuario_status_categoria_transacao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='comum.usuario'),
        ),
    ]
